#include "frontend/core_manager.h"
#include "platform/psp/fs_psp.h"
#include "runtime/host_services.h"
#include "runtime/log.h"

#include <cstdio>
#include <cstring>

#ifdef RS_STATIC_CORES
/* Generated by cores/CMakeLists.txt: extern entry declarations plus the
 * RS_STATIC_CORE_TABLE list. */
#include "rs_static_cores.inc"
#else
#include <pspkernel.h>
#include <pspmodulemgr.h>
#endif

namespace rs {

namespace {
bool validApi(const RSCoreAPI* api) {
    return api && api->api_version == RS_CORE_API_VERSION &&
           api->name && api->version && api->systems &&
           api->init && api->shutdown && api->load_rom && api->unload_rom &&
           api->reset && api->run_frame && api->get_frame &&
           api->state_size && api->state_save && api->state_load &&
           api->sram_size && api->sram_data && api->sram_dirty &&
           api->set_option;
}
}  // namespace

#ifdef RS_STATIC_CORES

int CoreManager::staticCoreCount() {
    return int(sizeof(RS_STATIC_CORE_TABLE) / sizeof(RS_STATIC_CORE_TABLE[0]));
}

const RSCoreAPI* CoreManager::staticCoreApi(int i) {
    return RS_STATIC_CORE_TABLE[i].getApi();
}

bool CoreManager::loadCore(const CoreInfo& info) {
    unloadCore();
    const char* name = info.name.c_str();
    for (const auto& entry : RS_STATIC_CORE_TABLE) {
        if (std::strcmp(entry.name, name) == 0) {
            const RSCoreAPI* api = entry.getApi();
            if (!validApi(api)) {
                std::snprintf(m_error, sizeof m_error,
                              "core '%s': api version mismatch", name);
                return false;
            }
            m_core = EmulatorCore(api);
            RS_LOGI("core: '%s' ready (static)", name);
            return true;
        }
    }
    std::snprintf(m_error, sizeof m_error, "core '%s' not linked in", name);
    return false;
}

bool CoreManager::initialize(const RSHostAPI* host) {
    if (!m_core.valid() || m_initialized) return false;
    m_initialized = m_core.initialize(host);
    return m_initialized;
}

void CoreManager::unloadCore() {
    if (m_core.valid() && m_initialized) m_core.shutdown();
    m_initialized = false;
    m_core = EmulatorCore();
}

#else  /* PRX loading */

bool CoreManager::loadCore(const CoreInfo& info) {
    unloadCore();

    const char* name = info.name.c_str();
    char path[128];
    std::snprintf(path, sizeof path, "%s/cores/%s.prx", fs::ROOT, name);

    const SceUID mod = sceKernelLoadModule(path, 0, nullptr);
    if (mod < 0) {
        std::snprintf(m_error, sizeof m_error, "load %s failed (%08x)", path,
                      unsigned(mod));
        RS_LOGE("core: %s", m_error);
        return false;
    }

    /* The module writes its API table pointer into this slot during
     * module_start (the address travels as the start argument). */
    static const RSCoreAPI* volatile s_apiSlot;
    s_apiSlot = nullptr;
    const void* slotAddr = (const void*)&s_apiSlot;

    int status = 0;
    const int ret = sceKernelStartModule(mod, sizeof slotAddr,
                                         (void*)&slotAddr, &status, nullptr);
    if (ret < 0 || !s_apiSlot) {
        std::snprintf(m_error, sizeof m_error,
                      "start %s failed (%08x, api %p)", name, unsigned(ret),
                      (const void*)s_apiSlot);
        RS_LOGE("core: %s", m_error);
        sceKernelUnloadModule(mod);
        return false;
    }

    if (!validApi(s_apiSlot)) {
        std::snprintf(m_error, sizeof m_error,
                      "core '%s': api v%u, host v%u", name,
                      unsigned(s_apiSlot->api_version),
                      unsigned(RS_CORE_API_VERSION));
        RS_LOGE("core: %s", m_error);
        sceKernelStopModule(mod, 0, nullptr, &status, nullptr);
        sceKernelUnloadModule(mod);
        return false;
    }

    m_moduleId = mod;
    m_core = EmulatorCore(s_apiSlot);
    RS_LOGI("core: '%s' ready (prx %s)", name, path);
    return true;
}

bool CoreManager::initialize(const RSHostAPI* host) {
    if (!m_core.valid() || m_initialized) return false;
    m_initialized = m_core.initialize(host);
    return m_initialized;
}

void CoreManager::unloadCore() {
    if (m_core.valid() && m_initialized) m_core.shutdown();
    m_initialized = false;
    m_core = EmulatorCore();
    if (m_moduleId >= 0) {
        int status = 0;
        sceKernelStopModule(m_moduleId, 0, nullptr, &status, nullptr);
        sceKernelUnloadModule(m_moduleId);
        m_moduleId = -1;
        RS_LOGI("core: module unloaded");
    }
}

#endif  /* RS_STATIC_CORES */

}  // namespace rs
